projet_realisations:
    resource: "@ProjetRealisationBundle/Resources/config/routing.yml"
    prefix:   /

projet_inscription:
    resource: "@ProjetInscriptionBundle/Resources/config/routing.yml"
    prefix:   /

projet_video:
    resource: "@ProjetVideoBundle/Resources/config/routing.yml"
    prefix:   /

projet_chapeau:
    resource: "@ProjetChapeauBundle/Resources/config/routing.yml"
    prefix:   /

projet_base:
    resource: "@ProjetBaseBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin