parameters:
#    projet_chapeau.example.class: Projet\ChapeauBundle\Example

services:
#    projet_chapeau.example:
#        class: %projet_chapeau.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
