parameters:
#    projet_base.example.class: Projet\BaseBundle\Example

services:
    sonata.admin.Rubrique:
        class: Projet\BaseBundle\Admin\RubriqueAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Menu", label: "Rubriques" }
         
        arguments:
            - ~
            - Projet\BaseBundle\Entity\Rubriques
          
            - ~
        calls:
            - [ setTranslationDomain, [ProjetcmsPrincipal]]



    sonata.admin.Article:
        class: Projet\BaseBundle\Admin\ArticleAdmin
                
        tags:
           
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Articles" }
        arguments:
            - ~
          
            - Projet\BaseBundle\Entity\Articles
            - ~
        calls:
            - [ setTranslationDomain, [ProjetcmsPrincipal]]
  