<?php

namespace Projet\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoiaRepository extends EntityRepository
{
}
