parameters:
#    projet_base.example.class: Projet\BaseBundle\Example

services:
#    projet_base.example:
#        class: %projet_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
